### ISSUE TITLE
is  this repository is excluded from hacktoberfest?

### ISSUE THREAD

**Issue by Danuragtiwari** [avinash201199/Paid-Internship-List#106]
@avinash201199

**Comment by divyanshu1810** [comment]
no

**Comment by avinash201199** [comment]
no why ? @Danuragtiwari

**Comment by Danuragtiwari** [comment]
@avinash201199 because many of the repositories where I have made pull requests are excluded,I am very afraid to make new pr!!,I hope here are all fine

**Comment by Danuragtiwari** [comment]
@divyanshu1810

**Comment by avinash201199** [comment]
repositories are excluded only when people make mass pr or irrevelant pr , I'm reviewing every pr hope so everything goes well

**Comment by divyanshu1810** [comment]
please close this issue sir @avinash201199
