### ISSUE TITLE
HackerEarth Off Campus Drive Hiring-Freshers

### ISSUE THREAD

**Issue by coding-finesse** [avinash201199/Paid-Internship-List#16]
[**HackerEarth Off Campus Drive Hiring Freshers as Intern**](https://hackerearthjobs.hire.trakstar.com/jobs/fk0so2u/)

**Frontend Intern**

Company Name: HackerEarth
Work Location: BengaluruJob 
Type: Engineering Contract
Duration : 6-months
Stipend: 40,000 per month

**Comment by avinash201199** [comment]
Go ahead @coding-finesse :)
