### ISSUE TITLE
Create website for this repo - comment down to work on this issue 

### ISSUE THREAD

**Issue by avinash201199** [avinash201199/Paid-Internship-List#17]

**Comment by kishoreboddite** [comment]
Hi 
Im in for the project

**Comment by 17Moons** [comment]
i want to work on this too, please tell the techstack you are using @kishoreboddite and how much work have been done

**Comment by kishoreboddite** [comment]
@17Moons  limiting to vanilla javascript  but have plans for using react

**Comment by avinash201199** [comment]
Go ahead @kishoreboddite @17Moons
