### ISSUE TITLE
Website contribution

### ISSUE THREAD

**Issue by vinayBhoure** [avinash201199/Paid-Internship-List#200]
Hey Avinash, Please assign me website work so that i can contribute with  my HTML ,CSS knowledge.

**Comment by vinayBhoure** [comment]
Hi Avinash,
could you brief me how should i make your website.
It will more helpful if i contribute according to your need.It will save
time of both of us and help of get effective results.
JUST try to send me the layout or basic idea about websites . What
components you need in your website
.

**Comment by Manishgupta200** [comment]
I would like to contribute... Assign this task to me
